config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :searches
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  
  get '/signup', to: 'users#new'
  get '/', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/recent_haiku', to: 'static_pages#recent_haiku'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'microposts', to: 'searches#index'

  root 'static_pages#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">

		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>
		</div>

		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li> <%= msg %> </li>
			<% end %>
		</ul>


	</div>

<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<%= will_paginate @feed_items %>
		<ol class="microposts">
	    	<%= render @feed_items %>
	  	</ol>
 	 <%= will_paginate @feed_items %>

<% end %>

app/views/shared/_micropost_form.html.erb
	<%= form_for(@micropost) do |f| %>
	  <%= render 'shared/error_messages', object: f.object %>
	  <div class="field">

	    <%= f.text_area :content, placeholder: "Compose your haiku review here! 5 syllables in the first line, 7 syllables in the second line, and 5 syllables in the third line...", value: @content %>

		<%= f.hidden_field :title, placeholder: "title", value: @title %>

		<%= f.hidden_field :picture, placeholder: "picture", value: @picture %>

		<%= f.hidden_field :year, placeholder: "year", value: @year %>

		<%= f.hidden_field :movie_ref, placeholder: "movie_ref", value: @movie_ref %>

	  </div>
	  <%= f.submit "Post", class: "btn btn-primary" %>
	<% end %>

app/views/shared/_search_form.html.erb
      


      <div class = "search_form">
        <%= form_tag searches_path, :method => 'get' do %>
            <%= text_field_tag "movie", params["movie"],  placeholder: "Enter movie search term here..." %>
            <%= submit_tag "Search Movies", class: "btn btn-primary shrink", :name => nil %>
        <% end %>
      
      </div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    <%= "follower".pluralize(@user.followers.count) %>
  </a>
</div>

app/views/shared/_user_info.html.erb
<% if logged_in? %>

	<%= link_to gravatar_for(current_user, size: 60), current_user %>

	<h4><%= current_user.name %></h4>

	<span><%= link_to "view my profile", current_user %></span>

	<span><%= current_user.microposts.count %> Haiku</span>

<% end %>