config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :searches
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  
  get '/signup', to: 'users#new'
  get '/', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/recent_haiku', to: 'static_pages#recent_haiku'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'microposts', to: 'searches#index'

  root 'static_pages#home'

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def index 
		if params['movie'] != nil
			input = params['movie'].split(/ /).join('+').to_sym 
		end

		url = HTTParty.get"http://api.rottentomatoes.com/api/public/v1.0/movies.json?q=#{input}&page_limit=25&page=1&apikey=" + ENV["ROTTEN_TOMATOES_API_KEY"]


		@movie = JSON.parse(url.body)

		

	end

	def show
			@title = params[:title] ? params[:title] : Micropost.where(movie_ref: params[:id]).first.title 
			@picture = params[:picture] ? params[:picture] : Micropost.where(movie_ref: params[:id]).first.picture 
			@year = params[:year] ? params[:year] : Micropost.where(movie_ref: params[:id]).first.year 
			@movie_ref = params[:id]


	  		@micropost = current_user.microposts.build if logged_in?
	  		
	  		@microposts = Micropost.where(movie_ref: params[:id]).paginate(page: params[:page], :per_page => 10)



    end



end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/index.html.erb
<div class="row">
		


		

		<% if @movie['movies'].nil? %>

			<div class="col-md-4 col-md-offset-4">
				<h1>Movie Search</h1>
				<%= render 'shared/search_form' %>
			</div>
		<% else %>

		<div class="col-md-12">
			<% @movie['movies'].each do |movie| %>

			

			<div class = "microposts">

			<li>
				<img src=<%= movie['posters']['detailed']%> class="moviethumbnail"></img>

				<div class = "movietitle h3">
					<% title = movie['title'] %>
					<% year = movie['year']%>	
					<% params[:id] = movie['id'] %>
					<%= link_to movie['title'], search_path(params[:id], title: title, year: year, picture: movie['posters']['original']) %> <br><%= year %>
					
				</div>

				
				<div class="synopsis">	
					<%= movie['synopsis'] %>
				</div>

				
			</li>
		</div>
		<% end %>
		<% end %>
</div>
</div>

app/views/searches/show.html.erb
	<div class="row">
		<aside class="col-md-4">

			<% if logged_in? %>

				<section class="user_info">
					<%= render 'shared/user_info' %> 
				</section>

		    	<div>
					<%= render 'shared/micropost_form' %>
				</div>
			
			<% else %>


				<section id="please_log_in">
					<h4>Please <%= link_to "log in",login_path %> or <%= link_to "sign up", new_user_path %> to post a haiku review for this movie</h4>
				</section>

			<% end %>

		</aside>

	



		<div class="col-md-8">

			<div class="movietitle h3"><%= @title %>,  <%= @year %></div>


			<!-- this displays the microposts for the shown movie -->
			<div class="microposts">
	          	<%= will_paginate @microposts %>
	      		<ol class="microposts">
	        		<%= render @microposts %>
	      		</ol>
	      		<%= will_paginate @microposts %>
			</div>









		
		</div>
	</div>