config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :searches
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  
  get '/signup', to: 'users#new'
  get '/', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/recent_haiku', to: 'static_pages#recent_haiku'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'microposts', to: 'searches#index'

  root 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">

	<small>
		<div class="pull-left">
		<p>A General Assembly project by <%= link_to "John McDonald", "https://github.com/johnptmcdonald" %></p>
		</div>
		<nav>
			<ul>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
				<li><%= link_to "My Github", "https://github.com/johnptmcdonald" %></li>
			</ul>
		</nav>

	</small>
</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-default" role="navigation">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to 'Haiku Review', root_path, class: "navbar-brand" %>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	        <li><%= link_to 'About', about_path %></li>
	        <li><%= link_to 'Help', help_path %></li>
	        <li><%= link_to 'Recent Haiku', recent_haiku_path %></li>
	        <li><%= link_to 'Search Movies', searches_path %></li>
	        <% if logged_in? %>
	        	<li><%= link_to 'Users', users_path %></li>
	        	<li id="fat-menu" class="dropdown"> 
	        		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
	        			Account <b class="caret"></b></a>

	        		<ul class="dropdown-menu">
		                <li><%= link_to "Profile", current_user %></li>
		                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
		                <li class="divider"></li>
		                <li> <%= link_to "Log out", logout_path, method: "delete" %> </li>
		            </ul>
		        </li>

	
	     
	     	<% else %>
	     		<li><%= link_to "Log in", login_path %> </li>
	     	<% end %>
	      </ul>
	      
	      
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title><%= full_title(yield(:title)) %></title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render 'layouts/header' %>

	<div class='container'>
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %> "><%= message %> </div>
		<% end %>

		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>	
				
	</div>



</body>
</html>